version: "3.8"

services:
  puppeteer:
    build: .
    container_name: puppeteer-test
    volumes:
      - ./:/app
    # Если нужно взаимодействие между контейнерами
    networks:
      - localnet
    ports:
      - "3000:3000"

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin_pass
      - N8N_HOST=n8n.local
      - WEBHOOK_URL=http://localhost:5678
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./inst-flow.json:/home/node/inst-flow.json
    entrypoint: >
      sh -c "
        n8n import:workflow --input /home/node/inst-flow.json &&
        n8n start
      "
    networks:
      - localnet

volumes:
  n8n_data:

networks:
  localnet:

